import type { Metadata } from "next";
import { Orbit, Orbitron } from "next/font/google";
import "./globals.css";

const orbit = Orbit({
  variable: "--font-orbit",
  subsets: ["latin"],
  weight: "400", // Explicitly specifying the available weight
});

const orbitron = Orbitron({
  variable: "--font-orbitron",
  subsets: ["latin"],
  weight: "400", // Adjust if using another weight
});

export const metadata: Metadata = {
  title: "Larinlord",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${orbit.variable} ${orbitron.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}

